// Code generated by protoc-gen-go. DO NOT EDIT.
// source: communities.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommunityMember_Roles int32

const (
	CommunityMember_UNKNOWN_ROLE      CommunityMember_Roles = 0
	CommunityMember_ROLE_ALL          CommunityMember_Roles = 1
	CommunityMember_ROLE_MANAGE_USERS CommunityMember_Roles = 2
)

var CommunityMember_Roles_name = map[int32]string{
	0: "UNKNOWN_ROLE",
	1: "ROLE_ALL",
	2: "ROLE_MANAGE_USERS",
}

var CommunityMember_Roles_value = map[string]int32{
	"UNKNOWN_ROLE":      0,
	"ROLE_ALL":          1,
	"ROLE_MANAGE_USERS": 2,
}

func (x CommunityMember_Roles) String() string {
	return proto.EnumName(CommunityMember_Roles_name, int32(x))
}

func (CommunityMember_Roles) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{1, 0}
}

type CommunityPermissions_Access int32

const (
	CommunityPermissions_UNKNOWN_ACCESS  CommunityPermissions_Access = 0
	CommunityPermissions_NO_MEMBERSHIP   CommunityPermissions_Access = 1
	CommunityPermissions_INVITATION_ONLY CommunityPermissions_Access = 2
	CommunityPermissions_ON_REQUEST      CommunityPermissions_Access = 3
)

var CommunityPermissions_Access_name = map[int32]string{
	0: "UNKNOWN_ACCESS",
	1: "NO_MEMBERSHIP",
	2: "INVITATION_ONLY",
	3: "ON_REQUEST",
}

var CommunityPermissions_Access_value = map[string]int32{
	"UNKNOWN_ACCESS":  0,
	"NO_MEMBERSHIP":   1,
	"INVITATION_ONLY": 2,
	"ON_REQUEST":      3,
}

func (x CommunityPermissions_Access) String() string {
	return proto.EnumName(CommunityPermissions_Access_name, int32(x))
}

func (CommunityPermissions_Access) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{2, 0}
}

type Grant struct {
	CommunityId          []byte   `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	MemberId             []byte   `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	ChatId               string   `protobuf:"bytes,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Clock                uint64   `protobuf:"varint,4,opt,name=clock,proto3" json:"clock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Grant) Reset()         { *m = Grant{} }
func (m *Grant) String() string { return proto.CompactTextString(m) }
func (*Grant) ProtoMessage()    {}
func (*Grant) Descriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{0}
}

func (m *Grant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Grant.Unmarshal(m, b)
}
func (m *Grant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Grant.Marshal(b, m, deterministic)
}
func (m *Grant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Grant.Merge(m, src)
}
func (m *Grant) XXX_Size() int {
	return xxx_messageInfo_Grant.Size(m)
}
func (m *Grant) XXX_DiscardUnknown() {
	xxx_messageInfo_Grant.DiscardUnknown(m)
}

var xxx_messageInfo_Grant proto.InternalMessageInfo

func (m *Grant) GetCommunityId() []byte {
	if m != nil {
		return m.CommunityId
	}
	return nil
}

func (m *Grant) GetMemberId() []byte {
	if m != nil {
		return m.MemberId
	}
	return nil
}

func (m *Grant) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *Grant) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

type CommunityMember struct {
	Roles                []CommunityMember_Roles `protobuf:"varint,1,rep,packed,name=roles,proto3,enum=protobuf.CommunityMember_Roles" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CommunityMember) Reset()         { *m = CommunityMember{} }
func (m *CommunityMember) String() string { return proto.CompactTextString(m) }
func (*CommunityMember) ProtoMessage()    {}
func (*CommunityMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{1}
}

func (m *CommunityMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunityMember.Unmarshal(m, b)
}
func (m *CommunityMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunityMember.Marshal(b, m, deterministic)
}
func (m *CommunityMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunityMember.Merge(m, src)
}
func (m *CommunityMember) XXX_Size() int {
	return xxx_messageInfo_CommunityMember.Size(m)
}
func (m *CommunityMember) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunityMember.DiscardUnknown(m)
}

var xxx_messageInfo_CommunityMember proto.InternalMessageInfo

func (m *CommunityMember) GetRoles() []CommunityMember_Roles {
	if m != nil {
		return m.Roles
	}
	return nil
}

type CommunityPermissions struct {
	EnsOnly bool `protobuf:"varint,1,opt,name=ens_only,json=ensOnly,proto3" json:"ens_only,omitempty"`
	// https://gitlab.matrix.org/matrix-org/olm/blob/master/docs/megolm.md is a candidate for the algorithm to be used in case we want to have private communityal chats, lighter than pairwise encryption using the DR, less secure, but more efficient for large number of participants
	Private              bool                        `protobuf:"varint,2,opt,name=private,proto3" json:"private,omitempty"`
	Access               CommunityPermissions_Access `protobuf:"varint,3,opt,name=access,proto3,enum=protobuf.CommunityPermissions_Access" json:"access,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CommunityPermissions) Reset()         { *m = CommunityPermissions{} }
func (m *CommunityPermissions) String() string { return proto.CompactTextString(m) }
func (*CommunityPermissions) ProtoMessage()    {}
func (*CommunityPermissions) Descriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{2}
}

func (m *CommunityPermissions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunityPermissions.Unmarshal(m, b)
}
func (m *CommunityPermissions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunityPermissions.Marshal(b, m, deterministic)
}
func (m *CommunityPermissions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunityPermissions.Merge(m, src)
}
func (m *CommunityPermissions) XXX_Size() int {
	return xxx_messageInfo_CommunityPermissions.Size(m)
}
func (m *CommunityPermissions) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunityPermissions.DiscardUnknown(m)
}

var xxx_messageInfo_CommunityPermissions proto.InternalMessageInfo

func (m *CommunityPermissions) GetEnsOnly() bool {
	if m != nil {
		return m.EnsOnly
	}
	return false
}

func (m *CommunityPermissions) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

func (m *CommunityPermissions) GetAccess() CommunityPermissions_Access {
	if m != nil {
		return m.Access
	}
	return CommunityPermissions_UNKNOWN_ACCESS
}

type CommunityDescription struct {
	Clock                  uint64                        `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	Members                map[string]*CommunityMember   `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Permissions            *CommunityPermissions         `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	Identity               *ChatIdentity                 `protobuf:"bytes,5,opt,name=identity,proto3" json:"identity,omitempty"`
	Chats                  map[string]*CommunityChat     `protobuf:"bytes,6,rep,name=chats,proto3" json:"chats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	BanList                []string                      `protobuf:"bytes,7,rep,name=ban_list,json=banList,proto3" json:"ban_list,omitempty"`
	Categories             map[string]*CommunityCategory `protobuf:"bytes,8,rep,name=categories,proto3" json:"categories,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ArchiveMagnetlinkClock uint64                        `protobuf:"varint,9,opt,name=archive_magnetlink_clock,json=archiveMagnetlinkClock,proto3" json:"archive_magnetlink_clock,omitempty"`
	AdminSettings          *CommunityAdminSettings       `protobuf:"bytes,10,opt,name=admin_settings,json=adminSettings,proto3" json:"admin_settings,omitempty"`
	IntroMessage           string                        `protobuf:"bytes,11,opt,name=intro_message,json=introMessage,proto3" json:"intro_message,omitempty"`
	OutroMessage           string                        `protobuf:"bytes,12,opt,name=outro_message,json=outroMessage,proto3" json:"outro_message,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                      `json:"-"`
	XXX_unrecognized       []byte                        `json:"-"`
	XXX_sizecache          int32                         `json:"-"`
}

func (m *CommunityDescription) Reset()         { *m = CommunityDescription{} }
func (m *CommunityDescription) String() string { return proto.CompactTextString(m) }
func (*CommunityDescription) ProtoMessage()    {}
func (*CommunityDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{3}
}

func (m *CommunityDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunityDescription.Unmarshal(m, b)
}
func (m *CommunityDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunityDescription.Marshal(b, m, deterministic)
}
func (m *CommunityDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunityDescription.Merge(m, src)
}
func (m *CommunityDescription) XXX_Size() int {
	return xxx_messageInfo_CommunityDescription.Size(m)
}
func (m *CommunityDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunityDescription.DiscardUnknown(m)
}

var xxx_messageInfo_CommunityDescription proto.InternalMessageInfo

func (m *CommunityDescription) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *CommunityDescription) GetMembers() map[string]*CommunityMember {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *CommunityDescription) GetPermissions() *CommunityPermissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *CommunityDescription) GetIdentity() *ChatIdentity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *CommunityDescription) GetChats() map[string]*CommunityChat {
	if m != nil {
		return m.Chats
	}
	return nil
}

func (m *CommunityDescription) GetBanList() []string {
	if m != nil {
		return m.BanList
	}
	return nil
}

func (m *CommunityDescription) GetCategories() map[string]*CommunityCategory {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *CommunityDescription) GetArchiveMagnetlinkClock() uint64 {
	if m != nil {
		return m.ArchiveMagnetlinkClock
	}
	return 0
}

func (m *CommunityDescription) GetAdminSettings() *CommunityAdminSettings {
	if m != nil {
		return m.AdminSettings
	}
	return nil
}

func (m *CommunityDescription) GetIntroMessage() string {
	if m != nil {
		return m.IntroMessage
	}
	return ""
}

func (m *CommunityDescription) GetOutroMessage() string {
	if m != nil {
		return m.OutroMessage
	}
	return ""
}

type CommunityAdminSettings struct {
	PinMessageAllMembersEnabled bool     `protobuf:"varint,1,opt,name=pin_message_all_members_enabled,json=pinMessageAllMembersEnabled,proto3" json:"pin_message_all_members_enabled,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *CommunityAdminSettings) Reset()         { *m = CommunityAdminSettings{} }
func (m *CommunityAdminSettings) String() string { return proto.CompactTextString(m) }
func (*CommunityAdminSettings) ProtoMessage()    {}
func (*CommunityAdminSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{4}
}

func (m *CommunityAdminSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunityAdminSettings.Unmarshal(m, b)
}
func (m *CommunityAdminSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunityAdminSettings.Marshal(b, m, deterministic)
}
func (m *CommunityAdminSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunityAdminSettings.Merge(m, src)
}
func (m *CommunityAdminSettings) XXX_Size() int {
	return xxx_messageInfo_CommunityAdminSettings.Size(m)
}
func (m *CommunityAdminSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunityAdminSettings.DiscardUnknown(m)
}

var xxx_messageInfo_CommunityAdminSettings proto.InternalMessageInfo

func (m *CommunityAdminSettings) GetPinMessageAllMembersEnabled() bool {
	if m != nil {
		return m.PinMessageAllMembersEnabled
	}
	return false
}

type CommunityChat struct {
	Members              map[string]*CommunityMember `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Permissions          *CommunityPermissions       `protobuf:"bytes,2,opt,name=permissions,proto3" json:"permissions,omitempty"`
	Identity             *ChatIdentity               `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	CategoryId           string                      `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Position             int32                       `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CommunityChat) Reset()         { *m = CommunityChat{} }
func (m *CommunityChat) String() string { return proto.CompactTextString(m) }
func (*CommunityChat) ProtoMessage()    {}
func (*CommunityChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{5}
}

func (m *CommunityChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunityChat.Unmarshal(m, b)
}
func (m *CommunityChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunityChat.Marshal(b, m, deterministic)
}
func (m *CommunityChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunityChat.Merge(m, src)
}
func (m *CommunityChat) XXX_Size() int {
	return xxx_messageInfo_CommunityChat.Size(m)
}
func (m *CommunityChat) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunityChat.DiscardUnknown(m)
}

var xxx_messageInfo_CommunityChat proto.InternalMessageInfo

func (m *CommunityChat) GetMembers() map[string]*CommunityMember {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *CommunityChat) GetPermissions() *CommunityPermissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *CommunityChat) GetIdentity() *ChatIdentity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *CommunityChat) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

func (m *CommunityChat) GetPosition() int32 {
	if m != nil {
		return m.Position
	}
	return 0
}

type CommunityCategory struct {
	CategoryId           string   `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Position             int32    `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommunityCategory) Reset()         { *m = CommunityCategory{} }
func (m *CommunityCategory) String() string { return proto.CompactTextString(m) }
func (*CommunityCategory) ProtoMessage()    {}
func (*CommunityCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{6}
}

func (m *CommunityCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunityCategory.Unmarshal(m, b)
}
func (m *CommunityCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunityCategory.Marshal(b, m, deterministic)
}
func (m *CommunityCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunityCategory.Merge(m, src)
}
func (m *CommunityCategory) XXX_Size() int {
	return xxx_messageInfo_CommunityCategory.Size(m)
}
func (m *CommunityCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunityCategory.DiscardUnknown(m)
}

var xxx_messageInfo_CommunityCategory proto.InternalMessageInfo

func (m *CommunityCategory) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

func (m *CommunityCategory) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CommunityCategory) GetPosition() int32 {
	if m != nil {
		return m.Position
	}
	return 0
}

type CommunityInvitation struct {
	CommunityDescription []byte   `protobuf:"bytes,1,opt,name=community_description,json=communityDescription,proto3" json:"community_description,omitempty"`
	Grant                []byte   `protobuf:"bytes,2,opt,name=grant,proto3" json:"grant,omitempty"`
	ChatId               string   `protobuf:"bytes,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommunityInvitation) Reset()         { *m = CommunityInvitation{} }
func (m *CommunityInvitation) String() string { return proto.CompactTextString(m) }
func (*CommunityInvitation) ProtoMessage()    {}
func (*CommunityInvitation) Descriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{7}
}

func (m *CommunityInvitation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunityInvitation.Unmarshal(m, b)
}
func (m *CommunityInvitation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunityInvitation.Marshal(b, m, deterministic)
}
func (m *CommunityInvitation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunityInvitation.Merge(m, src)
}
func (m *CommunityInvitation) XXX_Size() int {
	return xxx_messageInfo_CommunityInvitation.Size(m)
}
func (m *CommunityInvitation) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunityInvitation.DiscardUnknown(m)
}

var xxx_messageInfo_CommunityInvitation proto.InternalMessageInfo

func (m *CommunityInvitation) GetCommunityDescription() []byte {
	if m != nil {
		return m.CommunityDescription
	}
	return nil
}

func (m *CommunityInvitation) GetGrant() []byte {
	if m != nil {
		return m.Grant
	}
	return nil
}

func (m *CommunityInvitation) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *CommunityInvitation) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type CommunityRequestToJoin struct {
	Clock                uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	EnsName              string   `protobuf:"bytes,2,opt,name=ens_name,json=ensName,proto3" json:"ens_name,omitempty"`
	ChatId               string   `protobuf:"bytes,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	CommunityId          []byte   `protobuf:"bytes,4,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommunityRequestToJoin) Reset()         { *m = CommunityRequestToJoin{} }
func (m *CommunityRequestToJoin) String() string { return proto.CompactTextString(m) }
func (*CommunityRequestToJoin) ProtoMessage()    {}
func (*CommunityRequestToJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{8}
}

func (m *CommunityRequestToJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunityRequestToJoin.Unmarshal(m, b)
}
func (m *CommunityRequestToJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunityRequestToJoin.Marshal(b, m, deterministic)
}
func (m *CommunityRequestToJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunityRequestToJoin.Merge(m, src)
}
func (m *CommunityRequestToJoin) XXX_Size() int {
	return xxx_messageInfo_CommunityRequestToJoin.Size(m)
}
func (m *CommunityRequestToJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunityRequestToJoin.DiscardUnknown(m)
}

var xxx_messageInfo_CommunityRequestToJoin proto.InternalMessageInfo

func (m *CommunityRequestToJoin) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *CommunityRequestToJoin) GetEnsName() string {
	if m != nil {
		return m.EnsName
	}
	return ""
}

func (m *CommunityRequestToJoin) GetChatId() string {
	if m != nil {
		return m.ChatId
	}
	return ""
}

func (m *CommunityRequestToJoin) GetCommunityId() []byte {
	if m != nil {
		return m.CommunityId
	}
	return nil
}

type CommunityRequestToJoinResponse struct {
	Clock                uint64                `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	CommunityId          []byte                `protobuf:"bytes,2,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	Community            *CommunityDescription `protobuf:"bytes,3,opt,name=community,proto3" json:"community,omitempty"`
	Accepted             bool                  `protobuf:"varint,4,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Grant                []byte                `protobuf:"bytes,5,opt,name=grant,proto3" json:"grant,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CommunityRequestToJoinResponse) Reset()         { *m = CommunityRequestToJoinResponse{} }
func (m *CommunityRequestToJoinResponse) String() string { return proto.CompactTextString(m) }
func (*CommunityRequestToJoinResponse) ProtoMessage()    {}
func (*CommunityRequestToJoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{9}
}

func (m *CommunityRequestToJoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunityRequestToJoinResponse.Unmarshal(m, b)
}
func (m *CommunityRequestToJoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunityRequestToJoinResponse.Marshal(b, m, deterministic)
}
func (m *CommunityRequestToJoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunityRequestToJoinResponse.Merge(m, src)
}
func (m *CommunityRequestToJoinResponse) XXX_Size() int {
	return xxx_messageInfo_CommunityRequestToJoinResponse.Size(m)
}
func (m *CommunityRequestToJoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunityRequestToJoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommunityRequestToJoinResponse proto.InternalMessageInfo

func (m *CommunityRequestToJoinResponse) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *CommunityRequestToJoinResponse) GetCommunityId() []byte {
	if m != nil {
		return m.CommunityId
	}
	return nil
}

func (m *CommunityRequestToJoinResponse) GetCommunity() *CommunityDescription {
	if m != nil {
		return m.Community
	}
	return nil
}

func (m *CommunityRequestToJoinResponse) GetAccepted() bool {
	if m != nil {
		return m.Accepted
	}
	return false
}

func (m *CommunityRequestToJoinResponse) GetGrant() []byte {
	if m != nil {
		return m.Grant
	}
	return nil
}

type CommunityMessageArchiveMagnetlink struct {
	Clock                uint64   `protobuf:"varint,1,opt,name=clock,proto3" json:"clock,omitempty"`
	MagnetUri            string   `protobuf:"bytes,2,opt,name=magnet_uri,json=magnetUri,proto3" json:"magnet_uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommunityMessageArchiveMagnetlink) Reset()         { *m = CommunityMessageArchiveMagnetlink{} }
func (m *CommunityMessageArchiveMagnetlink) String() string { return proto.CompactTextString(m) }
func (*CommunityMessageArchiveMagnetlink) ProtoMessage()    {}
func (*CommunityMessageArchiveMagnetlink) Descriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{10}
}

func (m *CommunityMessageArchiveMagnetlink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunityMessageArchiveMagnetlink.Unmarshal(m, b)
}
func (m *CommunityMessageArchiveMagnetlink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunityMessageArchiveMagnetlink.Marshal(b, m, deterministic)
}
func (m *CommunityMessageArchiveMagnetlink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunityMessageArchiveMagnetlink.Merge(m, src)
}
func (m *CommunityMessageArchiveMagnetlink) XXX_Size() int {
	return xxx_messageInfo_CommunityMessageArchiveMagnetlink.Size(m)
}
func (m *CommunityMessageArchiveMagnetlink) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunityMessageArchiveMagnetlink.DiscardUnknown(m)
}

var xxx_messageInfo_CommunityMessageArchiveMagnetlink proto.InternalMessageInfo

func (m *CommunityMessageArchiveMagnetlink) GetClock() uint64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *CommunityMessageArchiveMagnetlink) GetMagnetUri() string {
	if m != nil {
		return m.MagnetUri
	}
	return ""
}

type WakuMessage struct {
	Sig                  []byte   `protobuf:"bytes,1,opt,name=sig,proto3" json:"sig,omitempty"`
	Timestamp            uint64   `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Topic                []byte   `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload              []byte   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Padding              []byte   `protobuf:"bytes,5,opt,name=padding,proto3" json:"padding,omitempty"`
	Hash                 []byte   `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WakuMessage) Reset()         { *m = WakuMessage{} }
func (m *WakuMessage) String() string { return proto.CompactTextString(m) }
func (*WakuMessage) ProtoMessage()    {}
func (*WakuMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{11}
}

func (m *WakuMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WakuMessage.Unmarshal(m, b)
}
func (m *WakuMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WakuMessage.Marshal(b, m, deterministic)
}
func (m *WakuMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WakuMessage.Merge(m, src)
}
func (m *WakuMessage) XXX_Size() int {
	return xxx_messageInfo_WakuMessage.Size(m)
}
func (m *WakuMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WakuMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WakuMessage proto.InternalMessageInfo

func (m *WakuMessage) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *WakuMessage) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *WakuMessage) GetTopic() []byte {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *WakuMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *WakuMessage) GetPadding() []byte {
	if m != nil {
		return m.Padding
	}
	return nil
}

func (m *WakuMessage) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type WakuMessageArchiveMetadata struct {
	Version              uint32   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	From                 uint64   `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   uint64   `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	ContentTopic         [][]byte `protobuf:"bytes,4,rep,name=contentTopic,proto3" json:"contentTopic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WakuMessageArchiveMetadata) Reset()         { *m = WakuMessageArchiveMetadata{} }
func (m *WakuMessageArchiveMetadata) String() string { return proto.CompactTextString(m) }
func (*WakuMessageArchiveMetadata) ProtoMessage()    {}
func (*WakuMessageArchiveMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{12}
}

func (m *WakuMessageArchiveMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WakuMessageArchiveMetadata.Unmarshal(m, b)
}
func (m *WakuMessageArchiveMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WakuMessageArchiveMetadata.Marshal(b, m, deterministic)
}
func (m *WakuMessageArchiveMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WakuMessageArchiveMetadata.Merge(m, src)
}
func (m *WakuMessageArchiveMetadata) XXX_Size() int {
	return xxx_messageInfo_WakuMessageArchiveMetadata.Size(m)
}
func (m *WakuMessageArchiveMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_WakuMessageArchiveMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_WakuMessageArchiveMetadata proto.InternalMessageInfo

func (m *WakuMessageArchiveMetadata) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *WakuMessageArchiveMetadata) GetFrom() uint64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *WakuMessageArchiveMetadata) GetTo() uint64 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *WakuMessageArchiveMetadata) GetContentTopic() [][]byte {
	if m != nil {
		return m.ContentTopic
	}
	return nil
}

type WakuMessageArchive struct {
	Version              uint32                      `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Metadata             *WakuMessageArchiveMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Messages             []*WakuMessage              `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *WakuMessageArchive) Reset()         { *m = WakuMessageArchive{} }
func (m *WakuMessageArchive) String() string { return proto.CompactTextString(m) }
func (*WakuMessageArchive) ProtoMessage()    {}
func (*WakuMessageArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{13}
}

func (m *WakuMessageArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WakuMessageArchive.Unmarshal(m, b)
}
func (m *WakuMessageArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WakuMessageArchive.Marshal(b, m, deterministic)
}
func (m *WakuMessageArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WakuMessageArchive.Merge(m, src)
}
func (m *WakuMessageArchive) XXX_Size() int {
	return xxx_messageInfo_WakuMessageArchive.Size(m)
}
func (m *WakuMessageArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_WakuMessageArchive.DiscardUnknown(m)
}

var xxx_messageInfo_WakuMessageArchive proto.InternalMessageInfo

func (m *WakuMessageArchive) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *WakuMessageArchive) GetMetadata() *WakuMessageArchiveMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *WakuMessageArchive) GetMessages() []*WakuMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

type WakuMessageArchiveIndexMetadata struct {
	Version              uint32                      `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Metadata             *WakuMessageArchiveMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Offset               uint64                      `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Size                 uint64                      `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Padding              uint64                      `protobuf:"varint,5,opt,name=padding,proto3" json:"padding,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *WakuMessageArchiveIndexMetadata) Reset()         { *m = WakuMessageArchiveIndexMetadata{} }
func (m *WakuMessageArchiveIndexMetadata) String() string { return proto.CompactTextString(m) }
func (*WakuMessageArchiveIndexMetadata) ProtoMessage()    {}
func (*WakuMessageArchiveIndexMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{14}
}

func (m *WakuMessageArchiveIndexMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WakuMessageArchiveIndexMetadata.Unmarshal(m, b)
}
func (m *WakuMessageArchiveIndexMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WakuMessageArchiveIndexMetadata.Marshal(b, m, deterministic)
}
func (m *WakuMessageArchiveIndexMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WakuMessageArchiveIndexMetadata.Merge(m, src)
}
func (m *WakuMessageArchiveIndexMetadata) XXX_Size() int {
	return xxx_messageInfo_WakuMessageArchiveIndexMetadata.Size(m)
}
func (m *WakuMessageArchiveIndexMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_WakuMessageArchiveIndexMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_WakuMessageArchiveIndexMetadata proto.InternalMessageInfo

func (m *WakuMessageArchiveIndexMetadata) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *WakuMessageArchiveIndexMetadata) GetMetadata() *WakuMessageArchiveMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *WakuMessageArchiveIndexMetadata) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *WakuMessageArchiveIndexMetadata) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *WakuMessageArchiveIndexMetadata) GetPadding() uint64 {
	if m != nil {
		return m.Padding
	}
	return 0
}

type WakuMessageArchiveIndex struct {
	Archives             map[string]*WakuMessageArchiveIndexMetadata `protobuf:"bytes,1,rep,name=archives,proto3" json:"archives,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *WakuMessageArchiveIndex) Reset()         { *m = WakuMessageArchiveIndex{} }
func (m *WakuMessageArchiveIndex) String() string { return proto.CompactTextString(m) }
func (*WakuMessageArchiveIndex) ProtoMessage()    {}
func (*WakuMessageArchiveIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_f937943d74c1cd8b, []int{15}
}

func (m *WakuMessageArchiveIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WakuMessageArchiveIndex.Unmarshal(m, b)
}
func (m *WakuMessageArchiveIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WakuMessageArchiveIndex.Marshal(b, m, deterministic)
}
func (m *WakuMessageArchiveIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WakuMessageArchiveIndex.Merge(m, src)
}
func (m *WakuMessageArchiveIndex) XXX_Size() int {
	return xxx_messageInfo_WakuMessageArchiveIndex.Size(m)
}
func (m *WakuMessageArchiveIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_WakuMessageArchiveIndex.DiscardUnknown(m)
}

var xxx_messageInfo_WakuMessageArchiveIndex proto.InternalMessageInfo

func (m *WakuMessageArchiveIndex) GetArchives() map[string]*WakuMessageArchiveIndexMetadata {
	if m != nil {
		return m.Archives
	}
	return nil
}

func init() {
	proto.RegisterEnum("protobuf.CommunityMember_Roles", CommunityMember_Roles_name, CommunityMember_Roles_value)
	proto.RegisterEnum("protobuf.CommunityPermissions_Access", CommunityPermissions_Access_name, CommunityPermissions_Access_value)
	proto.RegisterType((*Grant)(nil), "protobuf.Grant")
	proto.RegisterType((*CommunityMember)(nil), "protobuf.CommunityMember")
	proto.RegisterType((*CommunityPermissions)(nil), "protobuf.CommunityPermissions")
	proto.RegisterType((*CommunityDescription)(nil), "protobuf.CommunityDescription")
	proto.RegisterMapType((map[string]*CommunityCategory)(nil), "protobuf.CommunityDescription.CategoriesEntry")
	proto.RegisterMapType((map[string]*CommunityChat)(nil), "protobuf.CommunityDescription.ChatsEntry")
	proto.RegisterMapType((map[string]*CommunityMember)(nil), "protobuf.CommunityDescription.MembersEntry")
	proto.RegisterType((*CommunityAdminSettings)(nil), "protobuf.CommunityAdminSettings")
	proto.RegisterType((*CommunityChat)(nil), "protobuf.CommunityChat")
	proto.RegisterMapType((map[string]*CommunityMember)(nil), "protobuf.CommunityChat.MembersEntry")
	proto.RegisterType((*CommunityCategory)(nil), "protobuf.CommunityCategory")
	proto.RegisterType((*CommunityInvitation)(nil), "protobuf.CommunityInvitation")
	proto.RegisterType((*CommunityRequestToJoin)(nil), "protobuf.CommunityRequestToJoin")
	proto.RegisterType((*CommunityRequestToJoinResponse)(nil), "protobuf.CommunityRequestToJoinResponse")
	proto.RegisterType((*CommunityMessageArchiveMagnetlink)(nil), "protobuf.CommunityMessageArchiveMagnetlink")
	proto.RegisterType((*WakuMessage)(nil), "protobuf.WakuMessage")
	proto.RegisterType((*WakuMessageArchiveMetadata)(nil), "protobuf.WakuMessageArchiveMetadata")
	proto.RegisterType((*WakuMessageArchive)(nil), "protobuf.WakuMessageArchive")
	proto.RegisterType((*WakuMessageArchiveIndexMetadata)(nil), "protobuf.WakuMessageArchiveIndexMetadata")
	proto.RegisterType((*WakuMessageArchiveIndex)(nil), "protobuf.WakuMessageArchiveIndex")
	proto.RegisterMapType((map[string]*WakuMessageArchiveIndexMetadata)(nil), "protobuf.WakuMessageArchiveIndex.ArchivesEntry")
}

func init() { proto.RegisterFile("communities.proto", fileDescriptor_f937943d74c1cd8b) }

var fileDescriptor_f937943d74c1cd8b = []byte{
	// 1291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0xef, 0xfa, 0x5f, 0xec, 0x67, 0x3b, 0x75, 0xa6, 0x6d, 0xba, 0x4d, 0x69, 0xe3, 0x2e, 0x20,
	0xb9, 0x42, 0xb8, 0x6a, 0x2a, 0xa4, 0x8a, 0x3f, 0x6d, 0xdd, 0xd4, 0x2a, 0xa6, 0x89, 0xdd, 0x8e,
	0x13, 0x0a, 0x3d, 0xb0, 0x5a, 0x7b, 0x27, 0xce, 0x28, 0xbb, 0xb3, 0x66, 0x67, 0x1c, 0x61, 0x0e,
	0xdc, 0x90, 0xf8, 0x08, 0x48, 0x1c, 0xf9, 0x28, 0x9c, 0xb8, 0x70, 0xe7, 0xc6, 0x91, 0x8f, 0x81,
	0x66, 0x66, 0x77, 0xbd, 0x76, 0xec, 0x34, 0x52, 0xc5, 0x69, 0xe7, 0xbd, 0x79, 0xef, 0x37, 0xef,
	0xff, 0x5b, 0xd8, 0x18, 0x06, 0xbe, 0x3f, 0x61, 0x54, 0x50, 0xc2, 0x9b, 0xe3, 0x30, 0x10, 0x01,
	0x2a, 0xaa, 0xcf, 0x60, 0x72, 0xb4, 0x75, 0x65, 0x78, 0xec, 0x08, 0x9b, 0xba, 0x84, 0x09, 0x2a,
	0xa6, 0xfa, 0xda, 0x3a, 0x85, 0xfc, 0xf3, 0xd0, 0x61, 0x02, 0xdd, 0x81, 0x4a, 0xac, 0x3c, 0xb5,
	0xa9, 0x6b, 0x1a, 0x75, 0xa3, 0x51, 0xc1, 0xe5, 0x84, 0xd7, 0x71, 0xd1, 0x4d, 0x28, 0xf9, 0xc4,
	0x1f, 0x90, 0x50, 0xde, 0x67, 0xd4, 0x7d, 0x51, 0x33, 0x3a, 0x2e, 0xba, 0x0e, 0x6b, 0x11, 0xbe,
	0x99, 0xad, 0x1b, 0x8d, 0x12, 0x2e, 0x48, 0xb2, 0xe3, 0xa2, 0xab, 0x90, 0x1f, 0x7a, 0xc1, 0xf0,
	0xc4, 0xcc, 0xd5, 0x8d, 0x46, 0x0e, 0x6b, 0xc2, 0xfa, 0xc5, 0x80, 0xcb, 0xbb, 0x31, 0xf6, 0xbe,
	0x02, 0x41, 0x9f, 0x40, 0x3e, 0x0c, 0x3c, 0xc2, 0x4d, 0xa3, 0x9e, 0x6d, 0xac, 0xef, 0x6c, 0x37,
	0x63, 0xd3, 0x9b, 0x0b, 0x92, 0x4d, 0x2c, 0xc5, 0xb0, 0x96, 0xb6, 0x1e, 0x41, 0x5e, 0xd1, 0xa8,
	0x06, 0x95, 0xc3, 0xee, 0x8b, 0x6e, 0xef, 0x75, 0xd7, 0xc6, 0xbd, 0xbd, 0x76, 0xed, 0x12, 0xaa,
	0x40, 0x51, 0x9e, 0xec, 0xd6, 0xde, 0x5e, 0xcd, 0x40, 0xd7, 0x60, 0x43, 0x51, 0xfb, 0xad, 0x6e,
	0xeb, 0x79, 0xdb, 0x3e, 0xec, 0xb7, 0x71, 0xbf, 0x96, 0xb1, 0xfe, 0x31, 0xe0, 0x6a, 0xf2, 0xc0,
	0x4b, 0x12, 0xfa, 0x94, 0x73, 0x1a, 0x30, 0x8e, 0x6e, 0x40, 0x91, 0x30, 0x6e, 0x07, 0xcc, 0x9b,
	0xaa, 0x70, 0x14, 0xf1, 0x1a, 0x61, 0xbc, 0xc7, 0xbc, 0x29, 0x32, 0x61, 0x6d, 0x1c, 0xd2, 0x53,
	0x47, 0x10, 0x15, 0x88, 0x22, 0x8e, 0x49, 0xf4, 0x05, 0x14, 0x9c, 0xe1, 0x90, 0x70, 0xae, 0xc2,
	0xb0, 0xbe, 0xf3, 0xe1, 0x12, 0x2f, 0x52, 0x8f, 0x34, 0x5b, 0x4a, 0x18, 0x47, 0x4a, 0xd6, 0x01,
	0x14, 0x34, 0x07, 0x21, 0x58, 0x8f, 0xbd, 0x69, 0xed, 0xee, 0xb6, 0xfb, 0xfd, 0xda, 0x25, 0xb4,
	0x01, 0xd5, 0x6e, 0xcf, 0xde, 0x6f, 0xef, 0x3f, 0x6d, 0xe3, 0xfe, 0x97, 0x9d, 0x97, 0x35, 0x03,
	0x5d, 0x81, 0xcb, 0x9d, 0xee, 0xd7, 0x9d, 0x83, 0xd6, 0x41, 0xa7, 0xd7, 0xb5, 0x7b, 0xdd, 0xbd,
	0x6f, 0x6b, 0x19, 0xb4, 0x0e, 0xd0, 0xeb, 0xda, 0xb8, 0xfd, 0xea, 0xb0, 0xdd, 0x3f, 0xa8, 0x65,
	0xad, 0x7f, 0x0b, 0x29, 0x17, 0x9f, 0x11, 0x3e, 0x0c, 0xe9, 0x58, 0xd0, 0x80, 0xcd, 0x92, 0x63,
	0xa4, 0x92, 0x83, 0xda, 0xb0, 0xa6, 0xf3, 0xca, 0xcd, 0x4c, 0x3d, 0xdb, 0x28, 0xef, 0x7c, 0xb4,
	0xc4, 0x89, 0x14, 0x4c, 0x53, 0xa7, 0x85, 0xb7, 0x99, 0x08, 0xa7, 0x38, 0xd6, 0x45, 0x4f, 0xa0,
	0x3c, 0x9e, 0x79, 0xaa, 0xe2, 0x51, 0xde, 0xb9, 0x7d, 0x7e, 0x3c, 0x70, 0x5a, 0x05, 0xed, 0x40,
	0x31, 0xae, 0x57, 0x33, 0xaf, 0xd4, 0x37, 0x53, 0xea, 0xaa, 0xbe, 0xf4, 0x2d, 0x4e, 0xe4, 0xd0,
	0x63, 0xc8, 0xcb, 0xca, 0xe3, 0x66, 0x41, 0x99, 0x7e, 0xf7, 0x2d, 0xa6, 0x4b, 0x94, 0xc8, 0x70,
	0xad, 0x27, 0xd3, 0x3e, 0x70, 0x98, 0xed, 0x51, 0x2e, 0xcc, 0xb5, 0x7a, 0xb6, 0x51, 0xc2, 0x6b,
	0x03, 0x87, 0xed, 0x51, 0x2e, 0x50, 0x17, 0x60, 0xe8, 0x08, 0x32, 0x0a, 0x42, 0x4a, 0xb8, 0x59,
	0x54, 0x0f, 0x34, 0xdf, 0xf6, 0x40, 0xa2, 0xa0, 0x5f, 0x49, 0x21, 0xa0, 0x87, 0x60, 0x3a, 0xe1,
	0xf0, 0x98, 0x9e, 0x12, 0xdb, 0x77, 0x46, 0x8c, 0x08, 0x8f, 0xb2, 0x13, 0x5b, 0x67, 0xa4, 0xa4,
	0x32, 0xb2, 0x19, 0xdd, 0xef, 0x27, 0xd7, 0xbb, 0x2a, 0x45, 0xcf, 0x61, 0xdd, 0x71, 0x7d, 0xca,
	0x6c, 0x4e, 0x84, 0xa0, 0x6c, 0xc4, 0x4d, 0x50, 0xf1, 0xa9, 0x2f, 0xb1, 0xa6, 0x25, 0x05, 0xfb,
	0x91, 0x1c, 0xae, 0x3a, 0x69, 0x12, 0xbd, 0x0f, 0x55, 0xca, 0x44, 0x18, 0xd8, 0x3e, 0xe1, 0xdc,
	0x19, 0x11, 0xb3, 0xac, 0xba, 0xb7, 0xa2, 0x98, 0xfb, 0x9a, 0x27, 0x85, 0x82, 0x49, 0x5a, 0xa8,
	0xa2, 0x85, 0x14, 0x33, 0x12, 0xda, 0x3a, 0x84, 0x4a, 0xba, 0x0e, 0x50, 0x0d, 0xb2, 0x27, 0x44,
	0x77, 0x4e, 0x09, 0xcb, 0x23, 0xba, 0x07, 0xf9, 0x53, 0xc7, 0x9b, 0xe8, 0x9e, 0x29, 0xef, 0xdc,
	0x58, 0xd9, 0xe0, 0x58, 0xcb, 0x7d, 0x9a, 0x79, 0x68, 0x6c, 0xbd, 0x02, 0x98, 0xe5, 0x68, 0x09,
	0xe8, 0xc7, 0xf3, 0xa0, 0xd7, 0x97, 0x80, 0x4a, 0xfd, 0x34, 0xe4, 0x1b, 0xb8, 0xbc, 0x90, 0x95,
	0x25, 0xb8, 0xf7, 0xe7, 0x71, 0x6f, 0x2e, 0xc3, 0xd5, 0x20, 0xd3, 0x14, 0xb6, 0xf5, 0x1d, 0x6c,
	0x2e, 0x0f, 0x3c, 0x7a, 0x06, 0xdb, 0x63, 0xca, 0xe2, 0x10, 0xda, 0x8e, 0xe7, 0xd9, 0x51, 0xa7,
	0xd8, 0x84, 0x39, 0x03, 0x8f, 0xb8, 0xd1, 0x94, 0xb9, 0x39, 0xa6, 0x2c, 0x0a, 0x6a, 0xcb, 0xf3,
	0x92, 0x98, 0x2a, 0x11, 0xeb, 0xef, 0x0c, 0x54, 0xe7, 0x1c, 0x43, 0x8f, 0x66, 0xdd, 0x6a, 0xa8,
	0x8a, 0xfc, 0x60, 0x45, 0x08, 0x2e, 0xd6, 0xa6, 0x99, 0x77, 0x6b, 0xd3, 0xec, 0x05, 0xdb, 0x74,
	0x1b, 0xca, 0x51, 0x23, 0xa8, 0x75, 0x93, 0x53, 0x81, 0x8f, 0x7b, 0x43, 0x6e, 0x9b, 0x2d, 0x28,
	0x8e, 0x03, 0x4e, 0x65, 0x0f, 0xa9, 0xde, 0xcf, 0xe3, 0x84, 0xfe, 0x9f, 0x4a, 0xcd, 0x72, 0x61,
	0xe3, 0x4c, 0x6e, 0x17, 0x0d, 0x35, 0xce, 0x18, 0x8a, 0x20, 0xc7, 0x1c, 0x5f, 0xbf, 0x54, 0xc2,
	0xea, 0x3c, 0x67, 0x7c, 0x76, 0xde, 0x78, 0xeb, 0x57, 0x03, 0xae, 0x24, 0xcf, 0x74, 0xd8, 0x29,
	0x15, 0x8e, 0x9a, 0xc5, 0x0f, 0xe0, 0xda, 0x6c, 0x03, 0xbb, 0xb3, 0x09, 0x12, 0xad, 0xe2, 0xab,
	0xc3, 0x15, 0x03, 0x7c, 0x24, 0xf7, 0x77, 0xb4, 0x8f, 0x35, 0xb1, 0x7a, 0x19, 0xdf, 0x02, 0x18,
	0x4f, 0x06, 0x1e, 0x1d, 0xda, 0x32, 0x5e, 0x39, 0xa5, 0x53, 0xd2, 0x9c, 0x17, 0x64, 0x6a, 0xfd,
	0x6c, 0xa4, 0xaa, 0x17, 0x93, 0xef, 0x27, 0x84, 0x8b, 0x83, 0xe0, 0xab, 0x80, 0xae, 0xda, 0x14,
	0xd1, 0x8a, 0x4c, 0xf9, 0x2f, 0x57, 0x64, 0x57, 0x86, 0x60, 0xa5, 0x0d, 0x8b, 0x7f, 0x1a, 0xb9,
	0x33, 0x7f, 0x1a, 0xd6, 0x9f, 0x06, 0xdc, 0x5e, 0x6e, 0x07, 0x26, 0x7c, 0x1c, 0x30, 0x4e, 0x56,
	0xd8, 0xb3, 0x88, 0x9d, 0x39, 0xfb, 0x17, 0xf3, 0x39, 0x94, 0x12, 0xf2, 0x9c, 0x9d, 0x94, 0x0a,
	0x32, 0x9e, 0x29, 0xc8, 0xc4, 0xca, 0x4d, 0x3d, 0x16, 0x44, 0x1b, 0x5e, 0xc4, 0x09, 0x3d, 0xcb,
	0x45, 0x3e, 0x95, 0x0b, 0xeb, 0x1b, 0xb8, 0x93, 0x2a, 0x39, 0xdd, 0xd5, 0x8b, 0x33, 0x7d, 0x85,
	0x37, 0xb7, 0x00, 0xf4, 0x5a, 0xb0, 0x27, 0x21, 0x8d, 0xe2, 0x5b, 0xd2, 0x9c, 0xc3, 0x90, 0x5a,
	0xbf, 0x19, 0x50, 0x7e, 0xed, 0x9c, 0x4c, 0xe2, 0x29, 0x5d, 0x83, 0x2c, 0xa7, 0xa3, 0xa8, 0x5c,
	0xe4, 0x11, 0xbd, 0x07, 0x25, 0x41, 0x7d, 0xc2, 0x85, 0xe3, 0x8f, 0x95, 0x7e, 0x0e, 0xcf, 0x18,
	0xf2, 0x51, 0x11, 0x8c, 0xe9, 0x50, 0x45, 0xa1, 0x82, 0x35, 0xa1, 0x7e, 0x6d, 0x9c, 0xa9, 0x17,
	0x38, 0x71, 0x66, 0x62, 0x52, 0xdf, 0xb8, 0x2e, 0x65, 0xa3, 0xc8, 0xc3, 0x98, 0x94, 0x2d, 0x70,
	0xec, 0xf0, 0x63, 0xb3, 0xa0, 0xd8, 0xea, 0x6c, 0xfd, 0x04, 0x5b, 0x29, 0xe3, 0x62, 0x97, 0x89,
	0x70, 0x5c, 0x47, 0x38, 0x12, 0xeb, 0x94, 0x84, 0x3c, 0x2e, 0xef, 0x2a, 0x8e, 0x49, 0x89, 0x75,
	0x14, 0x06, 0x7e, 0x64, 0xae, 0x3a, 0xa3, 0x75, 0xc8, 0x88, 0x40, 0x99, 0x99, 0xc3, 0x19, 0x11,
	0x20, 0x4b, 0xa6, 0x99, 0x09, 0xc2, 0xc4, 0x81, 0x72, 0x20, 0x57, 0xcf, 0x36, 0x2a, 0x78, 0x8e,
	0x67, 0xfd, 0x6e, 0x00, 0x3a, 0x6b, 0xc0, 0x39, 0x0f, 0x3f, 0x81, 0xa2, 0x1f, 0x99, 0x17, 0x4d,
	0x8d, 0xd4, 0x20, 0x5d, 0xed, 0x0a, 0x4e, 0xb4, 0xd0, 0x7d, 0x89, 0xa0, 0x64, 0xe4, 0xdf, 0x8e,
	0x1c, 0xc5, 0xd7, 0x96, 0x22, 0xe0, 0x44, 0xcc, 0xfa, 0xc3, 0x80, 0xed, 0xb3, 0xd8, 0x1d, 0xe6,
	0x92, 0x1f, 0x2e, 0x10, 0xab, 0x77, 0x37, 0x79, 0x13, 0x0a, 0xc1, 0xd1, 0x11, 0x27, 0x22, 0x8a,
	0x6e, 0x44, 0xc9, 0x2c, 0x70, 0xfa, 0x23, 0x89, 0x7e, 0xda, 0xd5, 0x79, 0x31, 0xff, 0xb9, 0x24,
	0xff, 0xd6, 0x5f, 0x06, 0x5c, 0x5f, 0xe1, 0x05, 0x7a, 0x01, 0xc5, 0xe8, 0x1f, 0x26, 0xde, 0x4f,
	0xf7, 0xce, 0xb3, 0x51, 0x29, 0x35, 0x23, 0x22, 0x5a, 0x55, 0x09, 0xc0, 0xd6, 0x11, 0x54, 0xe7,
	0xae, 0x96, 0x4c, 0xfe, 0xc7, 0xf3, 0x93, 0xff, 0xee, 0x5b, 0x1f, 0x4b, 0xa2, 0x32, 0xdb, 0x04,
	0x4f, 0xab, 0x6f, 0xca, 0xcd, 0x7b, 0x9f, 0xc5, 0x9a, 0x83, 0x82, 0x3a, 0x3d, 0xf8, 0x2f, 0x00,
	0x00, 0xff, 0xff, 0x09, 0x48, 0x9b, 0x39, 0x60, 0x0d, 0x00, 0x00,
}
